#pragma once

#include "hidapi_cfgmgr32.h"
#include "hidapi_hidsdi.h"

#ifndef HIDAPI_USE_DDK

int lookup_functions();
void free_library_handles();

extern HidD_GetHidGuid_ HidD_GetHidGuid;
extern HidD_GetAttributes_ HidD_GetAttributes;
extern HidD_GetSerialNumberString_ HidD_GetSerialNumberString;
extern HidD_GetManufacturerString_ HidD_GetManufacturerString;
extern HidD_GetProductString_ HidD_GetProductString;
extern HidD_SetFeature_ HidD_SetFeature;
extern HidD_GetFeature_ HidD_GetFeature;
extern HidD_GetInputReport_ HidD_GetInputReport;
extern HidD_GetIndexedString_ HidD_GetIndexedString;
extern HidD_GetPreparsedData_ HidD_GetPreparsedData;
extern HidD_FreePreparsedData_ HidD_FreePreparsedData;
extern HidP_GetCaps_ HidP_GetCaps;
extern HidD_SetNumInputBuffers_ HidD_SetNumInputBuffers;

extern CM_Locate_DevNodeW_ CM_Locate_DevNodeW;
extern CM_Get_Parent_ CM_Get_Parent;
extern CM_Get_DevNode_PropertyW_ CM_Get_DevNode_PropertyW;
extern CM_Get_Device_Interface_PropertyW_ CM_Get_Device_Interface_PropertyW;
extern CM_Get_Device_Interface_List_SizeW_ CM_Get_Device_Interface_List_SizeW;
extern CM_Get_Device_Interface_ListW_ CM_Get_Device_Interface_ListW;

#endif  // HIDAPI_USE_DDK